name: smuctblooddonation
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  intl: ^0.19.0

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  google_sign_in:
  animated_splash_screen: ^1.3.0
  another_carousel_pro: ^1.0.2
  image_picker: ^1.0.6
  webview_flutter: ^4.7.0
  http:
  flutter_local_notifications: ^17.1.1
  flutter_timezone: ^1.0.8
  rxdart: ^0.27.7
  app_settings: ^5.1.1
  firebase_messaging: ^14.9.1
  share: ^2.0.4
  flutter_launcher_icons:




dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

  
  
  
  
  
flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/