// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-zG6974bKDxm724pnulZg9qzPDYjzJI',
    appId: '1:386986152886:web:8781326999376fe68d2717',
    messagingSenderId: '386986152886',
    projectId: 'smuct-blood-donation-bd409',
    authDomain: 'smuct-blood-donation-bd409.firebaseapp.com',
    storageBucket: 'smuct-blood-donation-bd409.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACrRjgoNvFpC5DzptWuwKE2ZeLoZKtk5Q',
    appId: '1:386986152886:android:542ceb01600d82a78d2717',
    messagingSenderId: '386986152886',
    projectId: 'smuct-blood-donation-bd409',
    storageBucket: 'smuct-blood-donation-bd409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8gZKPfW3P7h2acUKIE6YrIqfCFNtEQG8',
    appId: '1:386986152886:ios:8379a0fee300e01e8d2717',
    messagingSenderId: '386986152886',
    projectId: 'smuct-blood-donation-bd409',
    storageBucket: 'smuct-blood-donation-bd409.appspot.com',
    iosBundleId: 'com.example.smuctblooddonation',
  );
}
